name: ElixirPotion
main: me.drakonn.ElixirPotion.ElixirPotion
version: 1.2
author: Drakonn
commands:
  pot:
    description: Stacks all potions in the players inventory
    permission: elexirpotions.stack